### ISSUE TITLE
Старые подкасты

### ISSUE THREAD

**Issue by vadimcoder** [web-standards-ru/podcasts-list#20]
У вас в списке есть подкасты, которые не обновляются уже очень долго, например, [Frontflip](http://frontflip.me/) не обновляется с 2016. Храните по историческим причинам 😃? Может есть смысл актуализировать?

**Comment by pepelsbey** [comment]
Если подкасты перестают быть доступны по ссылкам — есть смысл их удалить. Если их по-прежнему можно послушать, то зачем?
